[package]
name = "rvv-encode"
version = "0.1.0"
authors = ["Linfeng Qian <thewawar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.1.0"
pest_derive = "2.1.0"
anyhow = "1.0.44"